from fastapi import APIRouter
from pydantic import BaseModel
from typing import Optional
from datetime import datetime
from data.demo_data import MACHINES, generate_anomalies, get_predictions, QUALITY_SCORE_BREAKDOWN, get_recommendations

router = APIRouter()

class ReportRequest(BaseModel):
    report_type: str = "quality_report"
    audience: str = "quality_engineer"
    line_id: Optional[str] = "LINE_A"
    include_recommendations: bool = True

@router.post("/generate")
def generate_report(req: ReportRequest):
    now = datetime.now()
    anomalies = generate_anomalies()
    predictions = get_predictions()
    recs = get_recommendations()
    quality = QUALITY_SCORE_BREAKDOWN

    active_anomalies = [a for a in anomalies if a["status"] == "active"]
    active_predictions = [p for p in predictions if p["status"] == "active"]

    report = {
        "id": f"RPT-{now.strftime('%Y%m%d%H%M%S')}",
        "generated_at": now.isoformat(),
        "generated_by": "ForgeGuard AI — Reporting Agent",
        "ibm_model": "IBM Granite 13B Instruct",
        "report_type": req.report_type,
        "audience": req.audience,
        "title": f"Quality Intelligence Report — {now.strftime('%B %d, %Y %H:%M')}",
        "production_summary": {
            "date": now.strftime("%Y-%m-%d"),
            "shift": "Day Shift",
            "line": req.line_id,
            "machines_monitored": len(MACHINES),
            "machines_active": len([m for m in MACHINES if m["status"] != "offline"]),
            "production_volume": 1247,
            "first_pass_yield": 94.2
        },
        "quality_summary": {
            "overall_score": quality["overall"],
            "score_status": "Good",
            "components": quality["components"]
        },
        "anomaly_summary": {
            "total_detected": len(anomalies),
            "active": len(active_anomalies),
            "critical": sum(1 for a in anomalies if a["severity"] == "critical"),
            "events": [{"id": a["id"], "machine": a["machine_name"], "parameter": a["parameter"], "severity": a["severity"]} for a in active_anomalies]
        },
        "defect_predictions": [
            {
                "machine": p["machine_name"],
                "defect_type": p["defect_type"],
                "probability": p["probability"],
                "risk": p["risk_level"],
                "confidence": p["confidence"]
            } for p in active_predictions
        ],
        "root_causes": [
            {
                "prediction": p["defect_type"],
                "factors": p["contributing_factors"][:3],
                "explanation": p["explanation"]
            } for p in active_predictions
        ],
        "recommendations": [
            {
                "id": r["id"],
                "number": r["number"],
                "issue": r["issue"],
                "actions": [a["description"] for a in r["actions"]],
                "expected_impact": r["expected_impact"],
                "status": r["status"]
            } for r in recs
        ],
        "machine_status": [
            {
                "id": m["id"],
                "name": m["name"],
                "status": m["status"],
                "health": m["health"],
                "vibration": m["vibration"],
                "temperature": m["temperature"]
            } for m in MACHINES
        ],
        "ai_narrative": f"""
**Executive Summary**

During this production session, the ForgeGuard AI system detected {len(active_anomalies)} active anomalies 
across the monitored production floor. The most critical condition is on Machine M-03 (CNC Mill Unit 3) 
where a combined temperature and vibration anomaly has been identified with an 82% probability of causing 
dimensional deviation within the next 35 production cycles.

**Key Findings**

Machine M-03 is currently exhibiting multi-parameter anomalies: temperature has drifted 6.8°C above 
process baseline to 251.3°C, and vibration has escalated to 8.7 mm/s (limit: 6.0 mm/s). AI Root Cause 
Analysis identifies the primary contributors as temperature drift (42%), machine vibration (28%), material 
moisture (18%), and calibration drift (12%). Historical pattern matching shows 87% correlation with 
dimensional deviation events.

**AI Recommendations**

The Process Optimization Agent has generated Recommendation #024, proposing temperature reduction from 
240°C to 232°C and speed reduction from 1800 RPM to 1720 RPM. Modeling predicts this configuration 
would reduce defect probability from 82% to 31% and improve quality score from 78 to 93.

**Required Actions**

1. IMMEDIATE: Inspect M-03 spindle alignment and bearing condition.
2. HIGH PRIORITY: Schedule machine calibration — overdue by 24 days.
3. MONITOR: Review M-06 hydraulic pressure for potential seal degradation.

*This report was generated by ForgeGuard AI using IBM Granite 13B Instruct model with RAG-grounded 
manufacturing knowledge base. All recommendations require qualified engineer review before implementation.*
""",
        "disclaimer": "AI-generated quality report. All data reflects simulation-based analysis. Physical validation required before implementing corrective actions."
    }
    return report

@router.get("/history")
def get_report_history():
    from datetime import timedelta
    now = datetime.now()
    return [
        {"id": f"RPT-{i:04d}", "title": f"Quality Report — Shift {['A','B','C'][i%3]}", "generated_at": (now - timedelta(hours=i*8)).isoformat(), "audience": ["quality_engineer","production_manager","maintenance_engineer"][i%3], "status": "complete"}
        for i in range(1, 10)
    ]
